### ISSUE TITLE
Add support for multidimensional array or slice values

### ISSUE THREAD

**Issue by nnick14** [wangaoone/LambdaObjectstore#1]
```// Set New set API
// Internal error if result is false.
func (c *Client) Set(key string, val []byte) bool {
	_, ok := c.EcSet(key, val)
	return ok
}
```

Add support within the [client handler](https://github.com/wangaoone/LambdaObjectstore/blob/develop/client/client_handlers.go#L61) for input to either an array or slice of values (e.g. []float64 is input as a [][]byte value in the KV store) or even multi-dimensional arrays (e.g. [][]float64 is input as a [][][]byte value in the KV store).

This would make the cache more effective to use with ML training, as we could store a tensor row or even a mini batch of tensor rows of data.

**Comment by zhangjyr** [comment]
[]byte is an abstraction of a stream of raw bytes. Any data structure can be encoded into a []byte. As long as the underline protocol has no optimization for a structure like [][]byte or [][][]byte, all APIs that support a custom data type can do nothing but encode the data as []byte.

**Comment by nnick14** [comment]
That makes sense. I didn't think about that. Thanks for the clarification!
